### DISCUSSION TITLE
Controlling PRBs via xApp in USRP-based deployments

### DISCUSSION THREAD

**Discussion by dpliatsios** [srsran/oran-sc-ric#50] [Q&A] [answered]
I have deployed a 5G SA using a USRP B210 device as RF frontend and connected 2 commercial UEs.

The simple_mon_xapp.py xApp reports the correct measurements.

However, the simple_rc_xapp.py xApp seems to send the control messages without any errors, however, I do not see any changes in the UE (e.g., reducing DL throughput).

I tried alternating between 100 and 1 max PRBs, but the throughput on the devices is the same in both cases.

Could you please provide any assistance on this?

Please let me know if you need further details/logs

**Comment by pgawlowicz** [comment]
Could you provide srsgnb logs?

**Reply by dpliatsios** [reply]
Thank you for the prompt reply.

Please find attached the gnb.log file:
[gnb.log](https://github.com/user-attachments/files/18061503/gnb.log)

The srsRAN build is based on the latest commit ([e5d5b44](https://github.com/srsran/srsRAN_Project/commit/e5d5b44b92cf18d1bd1736da0148e5f9cce3721d)).

I configured it to log only the error outputs, to avoid having a very large file. If more detailed logs are needed please let me know.

**Reply by pgawlowicz** [reply]
could you share your config?

**Reply by dpliatsios** [reply]
Sure!

Please find it attached: 
[config.txt](https://github.com/user-attachments/files/18062441/config.txt)

**Reply by pgawlowicz** [reply, marked as answer]
you did not enable e2sm_rc module, you can do it with:
```
e2sm_rc_enabled: true            # Enable KPM service module
```

**Reply by dpliatsios** [reply]
Thank you for the reply.

I added the parameter you suggested as follows:
```
e2:
    bind_addr: 10.0.2.1  
    enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
    e2sm_kpm_enabled: true            # Enable KPM service module
    e2sm_rc_enabled: true            # Enable KPM service module
    addr: 10.0.2.10      # RIC IP Address
    port: 36421         # RIC port
```

However, the same error shows in the log:
```
[E2      ] [I] Handling E2 PDU of type initiatingMessage
[E2      ] [I] E2AP SDU, "initiatingMessage.RICcontrolRequest"
[E2      ] [I] Received RIC Control Request
[E2      ] [E] RAN function ID not supported
[E2      ] [E] RAN function ID not supported
```

Is there any other parameter that I am missing?

**UPDATE:**
I tried rerunning gnb and now I receive the error in the terminal that I run the xApp
```
Received RIC_CONTROL_FAILURE
```
