### DISCUSSION TITLE
RSRP Reporting for multi cell setup (Issue with E2 KPM Style 3)

### DISCUSSION THREAD

**Discussion by Keilwerth11270** [srsran/oran-sc-ric#51] [General]
Hi all,

I need to subscribe to RSRP metrics for two cells. I have attached my gNB config file in a zip folder attached at the end of this post.

As far as I know, E2 KPM Style 3 allows for per cell metric reporting. I am attempting to subscribe to RSRP metrics using this function:
```
    @xAppBase.start_function
    def start(self, e2_node_id, metric_names):
        try:
            print("\n=== Starting Cell RSRP Monitor xApp ===")
    
            matching_conds = [
                {
                    'matchingCondChoice': ('testCondInfo', {
                        'testType': ('ul-rSRP', 'true'),
                        'testExpr': 'lessthan',
                        'testValue': ('valueInt', 1000)
                    })
                },
                {
                    'matchingCondChoice': ('measLabel', {
                        'noLabel': 'true',
                        'sliceID': {'sST': bytes.fromhex('08')},
                        'fiveQI': 64,
                        'qCI': 9
                    })
                }
            ]

# I came to the conclusion of using these values based on the output of the PCAPs 

            # Configure monitoring parameters 
            report_period = 2000
            granul_period = 999
            
            print(f"\nSubscription Configuration:")
            print(f"E2 Node ID: {e2_node_id}")
            print(f"Metrics: {metric_names}")
            print(f"Report Period: {report_period} ms")
            print(f"Granularity Period: {granul_period} ms")
            print(f"Matching Conditions: {matching_conds}")
            
            self.e2sm_kpm.subscribe_report_service_style_3(
                e2_node_id,
                report_period,
                matching_conds,
                metric_names[0],
                granul_period,
                self.my_subscription_callback
            )
            
            print("\nINFO: Successfully subscribed to RSRP measurements")
                
        except Exception as e:
            print(f"\nCRITICAL: Failed to start xApp")
            print(f"ERROR Details: {str(e)}")
            print(traceback.format_exc())
            raise
```

The output of my xApp (code also available in the zip file) is as follows:
```
=== Command Line Arguments ===
{
  "config": "",
  "http_server_port": 8091,
  "rmr_port": 4561,
  "e2_node_id": "gnb_001_001_0000019b",
  "ran_func_id": 2
}
1733711404520 7/RMR [INFO] ric message routing library on SI95 p=4561 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)

INFO: Initializing Cell Monitor xApp
INFO: Cell metrics tracking initialized

=== Starting Cell RSRP Monitor xApp ===

Subscription Configuration:
E2 Node ID: gnb_001_001_0000019b
Metrics: ['RSRP']
Report Period: 2000 ms
Granularity Period: 999 ms
Matching Conditions: [{'matchingCondChoice': ('testCondInfo', {'testType': ('ul-rSRP', 'true'), 'testExpr': 'lessthan', 'testValue': ('valueInt', 1000)})}, {'matchingCondChoice': ('measLabel', {'noLabel': 'true', 'sliceID': {'sST': b'\x08'}, 'fiveQI': 64, 'qCI': 9})}]
Successfully subscribed with Subscription ID:  2pxcwUMtiPRRQevT0hEGUE3xRUo

INFO: Successfully subscribed to RSRP measurements
Received Subscription ID to E2EventInstanceId mapping: 2pxcwUMtiPRRQevT0hEGUE3xRUo -> 1
{'response': 'OK', 'status': 200, 'payload': '{}', 'ctype': 'application/json', 'attachment': None, 'mode': 'plain'}
10.0.2.13 - - [09/Dec/2024 02:30:05] "POST /ric/v1/subscriptions/response HTTP/1.1" 200 -
```
After that, nothing else would print (where the RSRP metrics should have been printing), so I checked the RIC for any messages but saw that there were no errors:
```
ric_submgr          | RMR is ready now ...
ric_rtmgr_sim       | 2024/12/09 02:29:47 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnb_001_001_0000019b"]}] elapsed: 17.528µs
ric_rtmgr_sim       | 2024/12/09 02:29:47 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnb_001_001_0000019b"]}] elapsed: 6.503µs
ric_rtmgr_sim       | 2024/12/09 02:30:05 POST /ric/v1/handles/xapp-subscription-handle  body: {"address":"10.0.2.20","port":4561,"subscription_id":1} elapsed: 11.124µs
```
Which led me to think there were issues elsewhere.

There are errors in the E2 PCAP file. I have been struggling with getting the E2 message right for a while now, I am not sure any more how to fix my `matching_conds` to fulfill what the E2 interface wants of me... any help is appreciated, please let me know if more information is needed. 

[Here I have attached a zip file containing my NGAP/E2AP PCAPs, gNB config file, and xApp python file.](https://github.com/user-attachments/files/18055732/ngap_yml_e2ap_xapp.zip)

**Comment by pgawlowicz** [comment]
The matching conditions in Report Style 3 are not supported on the srsRAN side. Also, filtering measurements by cell ID is not implemented.

**Reply by Keilwerth11270** [reply]
Thanks for your quick response.

Here I have updated the start function:
```
    @xAppBase.start_function
    def start(self, e2_node_id, metric_names):
        try:
            print("\n=== Starting Cell RSRP Monitor xApp ===")


            report_period = 2000
            granul_period = 999

            print(f"\nSubscription Configuration:")
            print(f"E2 Node ID: {e2_node_id}")
            print(f"Metrics: {metric_names}")
            print(f"Report Period: {report_period} ms")
            print(f"Granularity Period: {granul_period} ms")
            print(f"Matching Conditions: None")


            self.e2sm_kpm.subscribe_report_service_style_3(
                e2_node_id,
                report_period,
                [],
                'ul-rSRP', # hardcoded
                granul_period,
                self.my_subscription_callback
            )

            print("\nINFO: Successfully subscribed to RSRP measurements")

        except Exception as e:
            print(f"\nCRITICAL: Failed to start xApp")
            print(f"ERROR Details: {str(e)}")
            print(traceback.format_exc())
            raise
```

Note that I matched the metric being requested in the [example KPM Monitoring xApp](https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/kpm_mon_xapp.py). However, now I get this print when I go to deploy the xApp:

```
=== Command Line Arguments ===
{
  "config": "",
  "http_server_port": 8091,
  "rmr_port": 4561,
  "e2_node_id": "gnb_001_001_0000019b",
  "ran_func_id": 2
}
1733751500050 57/RMR [INFO] ric message routing library on SI95 p=4561 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)

=== Starting Cell RSRP Monitor xApp ===

Subscription Configuration:
E2 Node ID: gnb_001_001_0000019b
Metrics: ['ul-rSRP']
Report Period: 2000 ms
Granularity Period: 999 ms
Matching Conditions: None

CRITICAL: Failed to start xApp
ERROR Details: Odd-length string
Traceback (most recent call last):
  File "./fourth_xapp.py", line 48, in start
    self.e2sm_kpm.subscribe_report_service_style_3(
  File "/opt/xApps/lib/e2sm_kpm_module.py", line 37, in subscribe_report_service_style_3
    action_def = self.e2sm_kpm_compiler.pack_action_def_format3(matchingConds, metric_names, granulPeriod, cell_global_id)
  File "/opt/xApps/lib/asn1/e2sm_kpm_packer.py", line 94, in pack_action_def_format3
    action_def = self.asn1_compiler.encode('E2SM-KPM-ActionDefinition', action_def)
  File "/usr/local/lib/python3.8/site-packages/asn1tools/compiler.py", line 142, in encode
    return bytes(type_.encode(data, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/asn1tools/codecs/per.py", line 1994, in encode
    return encoder.as_bytearray()
  File "/usr/local/lib/python3.8/site-packages/asn1tools/codecs/per.py", line 276, in as_bytearray
    return bytearray(binascii.unhexlify(value))
binascii.Error: Odd-length string
```

`cell_global_id` in the `pack_action_def_format3(matchingConds, metric_names, granulPeriod, cell_global_id)` is set to None by default and does not impact the function in any way. I was just trying something. I can also test again with the default `e2sm_kpm_module.py` file if you would like. 

I have attached my [E2AP PCAP file](https://github.com/user-attachments/files/18062268/e2ap.zip). If needed, I can also provide the full xApp code. I removed the matching conditions in the subscription message also, as you indicated.

Let me know if anything else is needed.
[Here is the full xApp code as well](https://github.com/user-attachments/files/18062292/xapp.txt).

Also, is this the best way to get RSRP measurements per cell? Style 1 is at the node level but upon testing the subscription, I would only get one RSRP value back even though two cells are deployed. I'm guessing that RSRP value was the serving cell's RSRP itself. Guidance on this matter is also appreciated as I would like to be able to subscribe to KPMs in multiple cells.

**Reply by pgawlowicz** [reply]
which srsRAN version (commit id) do you use?

**Reply by pgawlowicz** [reply]
also check this one:
https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/kpm_mon_xapp.py#L65

**Reply by Keilwerth11270** [reply]
Output of `git show --oneline -s` for srsRAN_Project directory:
```
1483bda30 (HEAD, tag: release_24_04) Update main
```
Same output for oran-sc-ric directory:
```
1356ee9 (HEAD -> main, origin/main, origin/HEAD) add option to run RIC on a separate host PC
````

Should I update to latest release or some specific commit? I was having some problems with the multi-cell configuration for 24.10, but I can try it again.

**Reply by pgawlowicz** [reply]
There were a lot of fixes recently in srsRAN in E2 agent. So i recommend updating it. 
Anyway, the issue seems to be on the xApp side, as the field cannot be encoded correctly. Please try to use the same matching condition as in the provided example.

**Reply by Keilwerth11270** [reply]
> also check this one: https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/kpm_mon_xapp.py#L65

```
    @xAppBase.start_function
    def start(self, e2_node_id, metric_names):
        try:
            print("\n=== Starting Cell RSRP Monitor xApp ===")


            report_period = 2000
            granul_period = 999

            print(f"\nSubscription Configuration:")
            print(f"E2 Node ID: {e2_node_id}")
            print(f"Metrics: {metric_names}")
            print(f"Report Period: {report_period} ms")
            print(f"Granularity Period: {granul_period} ms")
            print(f"Matching Conditions: None")


            self.e2sm_kpm.subscribe_report_service_style_3(
                e2_node_id,
                report_period,
                [{'matchingCondChoice': ('testCondInfo', {'testType': ('ul-rSRP', 'true'), 'testExpr': 'lessthan', 'testValue': ('valueInt', 1000)})}],
                'ul-rSRP',
                granul_period,
                self.my_subscription_callback
            )

            print("\nINFO: Successfully subscribed to RSRP measurements")

        except Exception as e:
            print(f"\nCRITICAL: Failed to start xApp")
            print(f"ERROR Details: {str(e)}")
            print(traceback.format_exc())
            raise
```

I put the matching conditions like what was given in the code block you pointed out. 

Per the original `kpm_mon_xapp`, since `metric_names` is only taking the first item, I believe the value should be `'DRB.UEThpUl'` by default, but I am not interested in the uplink throughput... Should I match that code exactly? I was still using `ul-rSRP` here as per the contents of the `testType`. 

From the E2 side, in the [PCAP](https://github.com/user-attachments/files/18062959/e2ap.zip) I am getting this error: `RICsubscriptionRequest[UNKNOWN PER: too long integer(per_normally_small_nonnegative_whole_number)][Malformed Packet]`

When I ran the code this time I did not get any error from the xApp side and no error from the RIC side either, the issue can be found in the provided PCAP.

**Reply by Keilwerth11270** [reply]
> There were a lot of fixes recently in srsRAN in E2 agent. So i recommend updating it. Anyway, the issue seems to be on the xApp side, as the field cannot be encoded correctly. Please try to use the same matching condition as in the provided example.

Okay give me a few minutes, I will update to the latest commit of srsRAN and try to match the `kpm_mon_xapp` in my code.

**Reply by pgawlowicz** [reply]
This matchingCond is used here only as a placeholder, as it is anyway not parsed/used in the srsgnb e2 agent. So it is only important for the xAPP to generate the message correctly.
I am not sure if Wireshark is correctly handling this part of the message. This needs to be investigated.

**Reply by Keilwerth11270** [reply]
```
X:~/srsRAN_Project$ git branch
* (HEAD detached at release_24_04)
  main
X:~/srsRAN_Project$ git checkout main
Previous HEAD position was 1483bda30 Update main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
X:~/srsRAN_Project$ git pull origin
Already up to date.
X:~/srsRAN_Project$
````

Now the situation is as such:
```
X:~/srsRAN_Project$ git show --oneline -s
e5d5b44b9 (HEAD -> main, origin/test, origin/main, origin/HEAD) Update main
```

Here is the config I am trying to run:
```
gnb_id: 411
gnb_id_bit_length: 32

ru_sdr:
  device_driver: uhd
  device_args: type=x300
  srate: 30.72
  lo_offset: 30.72
  clock: internal
  sync: internal
  tx_gain: 15
  rx_gain: 15

cell_cfg:
  dl_arfcn: 640000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  nof_antennas_dl: 1
  nof_antennas_ul: 1

cells:
  -
    pci: 1
    prach:
      prach_root_sequence_index: 0
  -
    pci: 2
    prach:
      prach_root_sequence_index: 64

cu_cp:
  amf:
    addr: 127.0.0.5
    bind_addr: 127.0.0.1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x19B0
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B1
            report_configs: [ 1 ]
      - nr_cell_id: 0x19B1
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B0
            report_configs: [ 2 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        #a3_offset_db: 3
        #a3_hysteresis_db: 0
        #a3_time_to_trigger_ms: 100

metrics:
  enable_json_metrics: true
  addr: 38.68.232.68
  port: 55555

log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: true
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/gnb_ngap.pcap
  e2ap_du_filename: /tmp/du_e2ap.pcap   # Optional TEXT (/tmp/du_e2ap.pcap). Path for E2AP CU PCAPs.
  e2ap_enable: true                    # Optional BOOLEAN (false). Enable/disable E2AP packet capture. Supported: [false, true].


e2:
  enable_du_e2: true
  addr: 10.0.2.10
  port: 36421
  bind_addr: 0.0.0.0
  e2sm_kpm_enabled: true
```

I am trying to follow the [configuration reference,](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html) but many of the configs are not matching.

Here are my attempts to progressively figure out what is needed from the config side:

```
X:~/srsRAN_Project/configs$ sudo gnb -c gnb_test.yml

--== srsRAN gNB (commit e5d5b44b9) ==--

Invalid CU-CP configuration. If report type is set to "event_triggered" then "event_triggered_report_type" must be set
srsRAN ERROR: Invalid configuration detected.

X:~/srsRAN_Project/configs$ sudo gnb -c gnb_test.yml

--== srsRAN gNB (commit e5d5b44b9) ==--

--event_triggered_report_type: rsrp not in {a1,a2,a3,a4,a5,a6}
Run with --help for more information.
X:~/srsRAN_Project/configs$ sudo gnb -c gnb_test.yml

--== srsRAN gNB (commit e5d5b44b9) ==--

Invalid event A3/A6 measurement report configuration.
srsRAN ERROR: Invalid configuration detected.

X:~/srsRAN_Project/configs$ sudo gnb -c gnb_test.yml

--== srsRAN gNB (commit e5d5b44b9) ==--

INI was not able to parse a3_offset_db
Run with --help for more information.
X:~/srsRAN_Project/configs$ sudo gnb -c gnb_test.yml

--== srsRAN gNB (commit e5d5b44b9) ==--

INI was not able to parse a3_hysteresis_db
Run with --help for more information.
X:~/srsRAN_Project/configs$ sudo gnb -c gnb_test.yml

--== srsRAN gNB (commit e5d5b44b9) ==--

INI was not able to parse a3_time_to_trigger_ms
Run with --help for more information.
X:~/srsRAN_Project/configs$ sudo gnb -c gnb_test.yml

--== srsRAN gNB (commit e5d5b44b9) ==--

Invalid event A3/A6 measurement report configuration.
srsRAN ERROR: Invalid configuration detected.
```
I commented out the hysteresis, offset, and time-to-trigger for the time being since the gNB was not able to parse those configs. 

Also from the xApp side, I have configured the metric to be hardcoded to the `'DRB.UeThpUl'` which would match the `kpm_mon_xapp`:
```
    @xAppBase.start_function
    def start(self, e2_node_id, metric_names):
        try:
            print("\n=== Starting Cell RSRP Monitor xApp ===")


            report_period = 2000
            granul_period = 999

            print(f"\nSubscription Configuration:")
            print(f"E2 Node ID: {e2_node_id}")
            print(f"Metrics: {metric_names}")
            print(f"Report Period: {report_period} ms")
            print(f"Granularity Period: {granul_period} ms")
            print(f"Matching Conditions: None")


            self.e2sm_kpm.subscribe_report_service_style_3(
                e2_node_id,
                report_period,
                [{'matchingCondChoice': ('testCondInfo', {'testType': ('ul-rSRP', 'true'), 'testExpr': 'lessthan', 'testValue': ('valueInt', 1000)})}],
                'DRB.UEThpUl',
                granul_period,
                self.my_subscription_callback
            )

            print("\nINFO: Successfully subscribed to RSRP measurements")

        except Exception as e:
            print(f"\nCRITICAL: Failed to start xApp")
            print(f"ERROR Details: {str(e)}")
            print(traceback.format_exc())
            raise
```

**Reply by pgawlowicz** [reply]
you have to update your config as there were some changes.

**Reply by Keilwerth11270** [reply]
> you have to update your config as there were some changes.

Is there any documentation for how to set up handover for the latest release? 

Here is where I am at now:
```
gnb_id: 411
gnb_id_bit_length: 32

ru_sdr:
  device_driver: uhd
  device_args: type=x300
  srate: 30.72
  lo_offset: 30.72
  clock: internal
  sync: internal
  tx_gain: 15
  rx_gain: 15

cell_cfg:
  dl_arfcn: 640000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  nof_antennas_dl: 1
  nof_antennas_ul: 1

cells:
  - pci: 1
    prach:
      prach_root_sequence_index: 0
  - pci: 2
    prach:
      prach_root_sequence_index: 64

cu_cp:
  amf:
    addr: 127.0.0.5
    bind_addr: 127.0.0.1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x19B0
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B1
            report_configs: [ 1, 2 ]
      - nr_cell_id: 0x19B1
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B0
            report_configs: [ 1, 2 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        a3_offset_db: 3
        a3_hysteresis_db: 0
        a3_time_to_trigger_ms: 100

metrics:
  enable_json_metrics: true
  addr: 38.68.232.68
  port: 55555

log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: true
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/gnb_ngap.pcap
  e2ap_du_filename: /tmp/du_e2ap.pcap
  e2ap_enable: true

e2:
  enable_du_e2: true
  addr: 10.0.2.10
  port: 36421
  bind_addr: 0.0.0.0
  e2sm_kpm_enabled: true
```

The issue has to do with these three configurations as of now:
```
        a3_offset_db: 3
        a3_hysteresis_db: 0
        a3_time_to_trigger_ms: 100
```

Commenting out all three of those configurations results in this:
```
--== srsRAN gNB (commit e5d5b44b9) ==--

Invalid event A3/A6 measurement report configuration.
srsRAN ERROR: Invalid configuration detected.
```

I am changing the names in different ways by removing `a3_` but there should be some documentation available. The current `handover_x310.yml` found at [this link](https://docs.srsran.com/projects/project/en/latest/tutorials/source/handover/source/index.html) is not updated to the latest version. 

When I try to run it to test, I get the same issue:
```
--== srsRAN gNB (commit e5d5b44b9) ==--

INI was not able to parse a3_report_type
Run with --help for more information.
```

The [configuration reference](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html) is also not updated. I was also unable to find much commentary on the latest release of srsRAN for handover configurations. Any guidance on fixing the configuration would be greatly appreciated.
