### DISCUSSION TITLE
Weird output from xApp rc

### DISCUSSION THREAD

**Discussion by fllay** [srsran/oran-sc-ric#64] [Q&A]
I try to write ric rc using the example `simple_ric.py` I modify in the following
```
#!/usr/bin/env python3

import time
import datetime
import argparse
import signal
from lib.xAppBase import xAppBase


class MyXapp(xAppBase):
    def __init__(self, http_server_port, rmr_port):
        super(MyXapp, self).__init__('', http_server_port, rmr_port)
        self.ue_dl_tx_data = {}
        self.min_prb_ratio = 1
        self.max_prb_ratio1 = 10
        self.max_prb_ratio2 = 100
        self.cur_ue_max_prb_ratio = {}
        self.dl_tx_data_threshold_mb = 20
        self.counter = 0

    def my_subscription_callback(self, e2_agent_id, subscription_id, indication_hdr, indication_msg, kpm_report_style, ue_id):
        indication_hdr = self.e2sm_kpm.extract_hdr_info(indication_hdr)
        meas_data = self.e2sm_kpm.extract_meas_data(indication_msg)

        print("Data Monitoring:")
        print("  E2SM_KPM RIC Indication Content:")
        print("  -ColletStartTime: ", indication_hdr['colletStartTime'])
        print("  -Measurements Data:")

        for ue_id, ue_meas_data in meas_data["ueMeasData"].items():
            print("  --UE_id: {}".format(ue_id))
            granulPeriod = ue_meas_data.get("granulPeriod", None)
            if granulPeriod is not None:
                print("  ---granulPeriod: {}".format(granulPeriod))

            for metric_name, values in ue_meas_data["measData"].items():
                print("  ---Metric: {}, Value: {:.1f} [MB]".format(metric_name, sum(values)/8/1000))

                if (metric_name == "DRB.RlcSduTransmittedVolumeDL"):
                    if ue_id in self.ue_dl_tx_data:
                        # Reported in kbits, convert to MBs.
                        self.ue_dl_tx_data[ue_id] += sum(values)/8/1000
                    else:
                        self.ue_dl_tx_data[ue_id] = sum(values)/8/1000

        print("")
        print("Control Logic:")
        print(" Tx Data Stats:")
        for ue_id, value in self.ue_dl_tx_data.items():
            min_prb_ratio = 1
            if(self.counter%3 == 0):
                max_prb_ratio = 10
            elif(self.counter%3 == 1):
                max_prb_ratio = 10
            elif(self.counter%3 == 2):
                max_prb_ratio = 10
            current_time = datetime.datetime.now()
            print("{} Send RIC Control Request to E2 node ID: {} for UE ID: {}, PRB_min_ratio: {}, PRB_max_ratio: {}".format(current_time.strftime("%H:%M:%S"), e2_node_id, ue_id, min_prb_ratio, max_prb_ratio))
            self.e2sm_rc.control_slice_level_prb_quota(e2_node_id, ue_id, min_prb_ratio, max_prb_ratio, dedicated_prb_ratio=100, ack_request=1)
            self.counter = self.counter + 1
        print("------------------------------------------------------------------")
        print("")


    # Mark the function as xApp start function using xAppBase.start_function decorator.
    # It is required to start the internal msg receive loop.
    @xAppBase.start_function
    def start(self, e2_node_id, kpm_report_style, ue_ids, metric_names):
        report_period = 1000
        granul_period = 1000

        subscription_callback = lambda agent, sub, hdr, msg: self.my_subscription_callback(agent, sub, hdr, msg, kpm_report_style, None)

        # Dummy condition that is always satisfied
        matchingUeConds = [{'testCondInfo': {'testType': ('ul-rSRP', 'true'), 'testExpr': 'lessthan', 'testValue': ('valueInt', 1000)}}]
        
        print("Subscribe to E2 node ID: {}, RAN func: e2sm_kpm, Report Style: {}, metrics: {}".format(e2_node_id, kpm_report_style, metric_names))
        self.e2sm_kpm.subscribe_report_service_style_4(e2_node_id, report_period, matchingUeConds, metric_names, granul_period, subscription_callback)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='My example xApp')
    parser.add_argument("--http_server_port", type=int, default=8090, help="HTTP server listen port")
    parser.add_argument("--rmr_port", type=int, default=4560, help="RMR port")
    parser.add_argument("--e2_node_id", type=str, default='gnbd_001_001_00019b_0', help="E2 Node ID")
    parser.add_argument("--ran_func_id", type=int, default=2, help="RAN function ID")
    parser.add_argument("--kpm_report_style", type=int, default=4, help="KPM Report Style ID")
    parser.add_argument("--ue_ids", type=str, default='0', help="UE ID")
    parser.add_argument("--metrics", type=str, default='DRB.RlcSduTransmittedVolumeDL', help="Metrics name as comma-separated string")

    args = parser.parse_args()
    e2_node_id = args.e2_node_id # TODO: get available E2 nodes from SubMgr, now the id has to be given.
    ran_func_id = args.ran_func_id # TODO: get available E2 nodes from SubMgr, now the id has to be given.
    ue_ids = list(map(int, args.ue_ids.split(","))) # Note: the UE id has to exist at E2 node!
    kpm_report_style = args.kpm_report_style
    metrics = args.metrics.split(",")

    # Create MyXapp.
    myXapp = MyXapp(args.http_server_port, args.rmr_port)
    myXapp.e2sm_kpm.set_ran_func_id(ran_func_id)

    # Connect exit signals.
    signal.signal(signal.SIGQUIT, myXapp.signal_handler)
    signal.signal(signal.SIGTERM, myXapp.signal_handler)
    signal.signal(signal.SIGINT, myXapp.signal_handler)

    # Start xApp.
    myXapp.start(e2_node_id, kpm_report_style, ue_ids, metrics)
    # Note: xApp will unsubscribe all active subscriptions at exit.

```
with gnb config file

```
cu_cp:
  amf:
    addr: 10.53.0.2
    port: 38412
    bind_addr: 192.168.68.30
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  clock: internal                                                       # Specify the clock source used by the RF.
  sync: internal                                                        # Specify the sync source used by the RF.
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 82                                                  # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                         #60          # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  ssb:
    ssb_period: 10
  pdsch:
    mcs_table: qam256
log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level:  warning                                               # Logging level applied to all layers.
  #phy_rx_symbols_filename: /tmp/iq.log

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.
```

and `e2` config file
```
e2:
    bind_addr: 10.0.2.1  
    enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
    e2sm_kpm_enabled: true            # Enable KPM service module
    e2sm_rc_enabled: true            # Enable KPM service module
    addr: 10.0.2.10      # RIC IP Address
    port: 36421         # RIC port

metrics:
  rlc_report_period: 1000           # Set reporting period to 1s
```
When I first run code above, I got
```
ata Monitoring:
  E2SM_KPM RIC Indication Content:
  -ColletStartTime:  2025-03-19 16:19:13
  -Measurements Data:
  --UE_id: 0
  ---granulPeriod: 1000
  ---Metric: DRB.RlcSduTransmittedVolumeDL, Value: 0.0 [MB]

Control Logic:
 Tx Data Stats:
16:19:13 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min_ratio: 1, PRB_max_ratio: 10
------------------------------------------------------------------

Received RIC_CONTROL_ACK
```

After I run `iperf` on the android device

```
Data Monitoring:
  E2SM_KPM RIC Indication Content:
  -ColletStartTime:  2025-03-19 16:19:29
  -Measurements Data:
  --UE_id: 2
  ---granulPeriod: 1000
  ---Metric: DRB.RlcSduTransmittedVolumeDL, Value: 0.0 [MB]

Control Logic:
 Tx Data Stats:
16:19:29 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min_ratio: 1, PRB_max_ratio: 10
16:19:29 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 10
16:19:29 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 2, PRB_min_ratio: 1, PRB_max_ratio: 10
------------------------------------------------------------------

Received RIC_CONTROL_ACK
Received RIC_CONTROL_FAILURE
Received RIC_CONTROL_FAILURE
```

now I got `Received RIC_CONTROL_FAILURE` from  `UE ID: 1,2` but `UE ID: 0` seem to be ok.  

Then the UE_ID that get ` RIC_CONTROL_ACK` changed to 1
```
Data Monitoring:
  E2SM_KPM RIC Indication Content:
  -ColletStartTime:  2025-03-19 16:30:45
  -Measurements Data:
  --UE_id: 3
  ---granulPeriod: 1000
  ---Metric: DRB.RlcSduTransmittedVolumeDL, Value: 0.0 [MB]

Control Logic:
 Tx Data Stats:
16:30:45 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min_ratio: 1, PRB_max_ratio: 10
16:30:45 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 10
16:30:45 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 2, PRB_min_ratio: 1, PRB_max_ratio: 10
16:30:45 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 3, PRB_min_ratio: 1, PRB_max_ratio: 10
------------------------------------------------------------------

Received RIC_CONTROL_FAILURE
Received RIC_CONTROL_ACK
Received RIC_CONTROL_FAILURE
Received RIC_CONTROL_FAILURE
Data Monitoring:
```

I am so confused. I observed that as long as I got `Received RIC_CONTROL_ACK` the  `PRB_max_ratio` setting seems to be ok 
as seen from iperf output. 
```
Accepted connection from 10.45.0.2, port 48260
[  5] local 192.168.68.30 port 5201 connected to 10.45.0.2 port 49950
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   902 KBytes  7.39 Mbits/sec                  
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   5.00-6.00   sec   695 KBytes  5.70 Mbits/sec                  
[  5]   6.00-7.00   sec   220 KBytes  1.80 Mbits/sec                  
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.03  sec  1.77 MBytes  1.48 Mbits/sec                  receiver
```

I also try `simple_rc_xapp.py` but I always got `Received RIC_CONTROL_FAILURE`. I am not sure `UE ID` is the problem since `simple_rc_xapp.py` allows only one `UE ID`. Any suggestion is appreciated.
