### ISSUE TITLE
No E2 connection error in real USRP

### ISSUE THREAD

**Issue by LoganCome** [srsran/oran-sc-ric#13]
Thanks a lot for the great resources!
I am deploying the project in real usrp and UE. 
I made the following Steps:

1. I deployed srsRAN and Open5GC, and I was able to establish and run a normal connection between the UE, gNB, and CN.
2. I installed the oran-sc-ric
3. I modified the gNB configuration with adding the following:
```
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable KPM service module
  addr: 10.0.2.10                   # RIC IP address
  bind_addr: 10.0.2.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port
```
However, I encountered the following problem when running the xApp:

1. The figure is the error output in app No E2 connectioand containers:
![Screenshot 2024-06-07 02:10:30](https://github.com/srsran/oran-sc-ric/assets/118045635/3c92ff4a-404c-4c69-b1ab-a382337b363f)
![Screenshot 2024-06-07 02:14:01](https://github.com/srsran/oran-sc-ric/assets/118045635/1551340a-92bd-4117-afad-ec7519650b05)
![Screenshot 2024-06-07 02:14:45](https://github.com/srsran/oran-sc-ric/assets/118045635/ae101c34-b672-40cb-8c8f-c4cda548f829)

2. The gNB log file
[gnb.log](https://github.com/user-attachments/files/15672890/gnb.log)

3. Contents of gNB configure file
[gnb_rf_x410_tdd_n78_20mhz.txt](https://github.com/user-attachments/files/15673547/gnb_rf_x410_tdd_n78_20mhz.txt)

The error is same with #4 , It seems like a problem that's easy to run into.
As you said in #3 , oran-sc-ric is independent with srsRAN and CN. However, for a real USRP and CN scenario, what adaptations are necessary? I suspect that my configuration has omissions.

Could you please help and guide me? I would really appreciate it.
