### ISSUE TITLE
Failure for running RIC

### ISSUE THREAD

**Issue by lingyan98** [srsran/oran-sc-ric#24]
When I run the docker-compose up. I got the following error, the other ric components can't connect to the dbaas. 
(base) bly@bly:~/Project/Research/ORAN/oran-sc-ric$ sudo docker-compose up
WARN[0000] /home/bly/Project/Research/ORAN/oran-sc-ric/docker-compose.yml: `version` is obsolete 
[+] Running 7/0
 ✔ Container ric_rtmgr_sim       Created                                                                                                                                               0.0s 
 ✔ Container ric_appmgr          Created                                                                                                                                               0.0s 
 ✔ Container ric_submgr          Created                                                                                                                                               0.0s 
 ✔ Container python_xapp_runner  Created                                                                                                                                               0.0s 
 ✔ Container ric_e2mgr           Created                                                                                                                                               0.0s 
 ✔ Container ric_dbaas           Created                                                                                                                                               0.0s 
 ✔ Container ric_e2term          Created                                                                                                                                               0.0s 
Attaching to python_xapp_runner, ric_appmgr, ric_dbaas, ric_e2mgr, ric_e2term, ric_rtmgr_sim, ric_submgr
ric_rtmgr_sim       | 2024/07/08 10:11:12 Server started on port 12020
ric_submgr          | {"ts":1720433472716,"crit":"INFO","id":"submgr","mdc":{"time":"2024-07-08T10:11:12"},"msg":"Using config file: /opt/config/submgr-config.yaml"}
ric_e2mgr           | {"ts":1720433473052,"crit":"INFO","id":"e2mgr","mdc":{"CONTAINER_NAME":"ric_e2mgr","HOST_NAME":"ric_e2mgr_host","PID":"1","POD_NAME":"e2mgr_pod","SERVICE_NAME":"ric_e2mgr_service","SYSTEM_NAME":"oran_sc_ric","e2mgr":"0.2.2","time":"2024-07-08T10:11:13Z"},"msg":"#app.main - Configuration {logging.logLevel: debug, http.port: 3800, rmr: { port: 3801, maxMsgSize: 65536}, routingManager.baseUrl: http://10.0.2.15:12020/ric/v1/handles/, notificationResponseBuffer: 100, bigRedButtonTimeoutSec: 5, maxRnibConnectionAttempts: 3, rnibRetryIntervalMs: 10, keepAliveResponseTimeoutMs: 4500, keepAliveDelayMs: 1500, e2tInstanceDeletionTimeoutMs: 15000,e2ResetTimeOutSec: 10,globalRicId: { ricId: AACCE, mcc: 001, mnc: 01}, rnibWriter: { stateChangeMessageChannel: RAN_CONNECTION_STATUS_CHANGE, ranManipulationChannel: RAN_MANIPULATION}"}
ric_e2mgr           | {"ts":1720433473052,"crit":"INFO","id":"e2mgr","mdc":{"CONTAINER_NAME":"ric_e2mgr","HOST_NAME":"ric_e2mgr_host","PID":"1","POD_NAME":"e2mgr_pod","SERVICE_NAME":"ric_e2mgr_service","SYSTEM_NAME":"oran_sc_ric","e2mgr":"0.2.2","time":"2024-07-08T10:11:13Z"},"msg":"Using config file: /opt/E2Manager/resources/configuration.yaml\n"}
ric_e2term          | 1720433473059 1/RMR [INFO] ric message routing library on SI95 p=38000 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
ric_dbaas           | 1:C 08 Jul 2024 10:11:13.062 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
ric_dbaas           | 1:C 08 Jul 2024 10:11:13.062 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
ric_dbaas           | 1:C 08 Jul 2024 10:11:13.062 # Configuration loaded
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.062 * Increased maximum number of open files to 10032 (it was originally set to 1024).
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.062 * monotonic clock: POSIX clock_gettime
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.063 * Running mode=standalone, port=6379.
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.063 # Server initialized
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.063 * Module 'exstrings' loaded from /usr/local/libexec/redismodule/libredismodule.so
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.064 * Loading RDB produced by version 6.2.14
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.064 * RDB age 169 seconds
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.064 * RDB memory usage when created 0.78 Mb
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.064 # Done loading RDB, keys loaded: 0, keys expired: 0.
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.064 * DB loaded from disk: 0.000 seconds
ric_dbaas           | 1:M 08 Jul 2024 10:11:13.064 * Ready to accept connections
ric_appmgr          | cp: cannot stat '/opt/ric/certificates/*': No such file or directory
ric_appmgr          | 2024/07/08 10:11:13 Using config file: /opt/ric/config/appmgr.yaml
ric_e2term          | {"ts":1720433481366,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"1","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error sending E2_TERM_INIT cause : RMR_ERR_NOENDPT - send//call could not find an endpoint based on msg type "}
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_e2mgr           | dial tcp 10.0.2.12:6379: i/o timeout
ric_appmgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_e2mgr exited with code 1
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout

**Comment by pgawlowicz** [comment]
try to remove the dbaas container and image and build again

**Comment by lingyan98** [comment]
> try to remove the dbaas container and image and build again

Thank you for your replaying. I have removed all containers and images. But the same error happend. Do I need modify any config file for running this project?

[+] Running 7/7
 ✔ Container ric_submgr          Created                                                                                                                                               0.2s 
 ✔ Container ric_e2mgr           Created                                                                                                                                               0.2s 
 ✔ Container ric_rtmgr_sim       Created                                                                                                                                               0.2s 
 ✔ Container ric_appmgr          Created                                                                                                                                               0.2s 
 ✔ Container python_xapp_runner  Created                                                                                                                                               0.2s 
 ✔ Container ric_e2term          Created                                                                                                                                               0.2s 
 ✔ Container ric_dbaas           Created                                                                                                                                               0.2s 
Attaching to python_xapp_runner, ric_appmgr, ric_dbaas, ric_e2mgr, ric_e2term, ric_rtmgr_sim, ric_submgr
ric_appmgr          | cp: cannot stat '/opt/ric/certificates/*': No such file or directory
ric_appmgr          | 2024/07/08 11:31:47 Using config file: /opt/ric/config/appmgr.yaml
ric_rtmgr_sim       | 2024/07/08 11:31:47 Server started on port 12020
ric_submgr          | {"ts":1720438307213,"crit":"INFO","id":"submgr","mdc":{"time":"2024-07-08T11:31:47"},"msg":"Using config file: /opt/config/submgr-config.yaml"}
ric_e2mgr           | {"ts":1720438307278,"crit":"INFO","id":"e2mgr","mdc":{"CONTAINER_NAME":"ric_e2mgr","HOST_NAME":"ric_e2mgr_host","PID":"1","POD_NAME":"e2mgr_pod","SERVICE_NAME":"ric_e2mgr_service","SYSTEM_NAME":"oran_sc_ric","e2mgr":"0.2.2","time":"2024-07-08T11:31:47Z"},"msg":"#app.main - Configuration {logging.logLevel: debug, http.port: 3800, rmr: { port: 3801, maxMsgSize: 65536}, routingManager.baseUrl: http://10.0.2.15:12020/ric/v1/handles/, notificationResponseBuffer: 100, bigRedButtonTimeoutSec: 5, maxRnibConnectionAttempts: 3, rnibRetryIntervalMs: 10, keepAliveResponseTimeoutMs: 4500, keepAliveDelayMs: 1500, e2tInstanceDeletionTimeoutMs: 15000,e2ResetTimeOutSec: 10,globalRicId: { ricId: AACCE, mcc: 001, mnc: 01}, rnibWriter: { stateChangeMessageChannel: RAN_CONNECTION_STATUS_CHANGE, ranManipulationChannel: RAN_MANIPULATION}"}
ric_e2mgr           | {"ts":1720438307278,"crit":"INFO","id":"e2mgr","mdc":{"CONTAINER_NAME":"ric_e2mgr","HOST_NAME":"ric_e2mgr_host","PID":"1","POD_NAME":"e2mgr_pod","SERVICE_NAME":"ric_e2mgr_service","SYSTEM_NAME":"oran_sc_ric","e2mgr":"0.2.2","time":"2024-07-08T11:31:47Z"},"msg":"Using config file: /opt/E2Manager/resources/configuration.yaml\n"}
ric_dbaas           | 1:C 08 Jul 2024 11:31:47.434 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
ric_dbaas           | 1:C 08 Jul 2024 11:31:47.434 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
ric_dbaas           | 1:C 08 Jul 2024 11:31:47.434 # Configuration loaded
ric_dbaas           | 1:M 08 Jul 2024 11:31:47.435 * Increased maximum number of open files to 10032 (it was originally set to 1024).
ric_dbaas           | 1:M 08 Jul 2024 11:31:47.435 * monotonic clock: POSIX clock_gettime
ric_dbaas           | 1:M 08 Jul 2024 11:31:47.435 * Running mode=standalone, port=6379.
ric_dbaas           | 1:M 08 Jul 2024 11:31:47.435 # Server initialized
ric_dbaas           | 1:M 08 Jul 2024 11:31:47.436 * Module 'exstrings' loaded from /usr/local/libexec/redismodule/libredismodule.so
ric_e2term          | 1720438307436 1/RMR [INFO] ric message routing library on SI95 p=38000 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
ric_dbaas           | 1:M 08 Jul 2024 11:31:47.436 * Ready to accept connections
ric_e2term          | {"ts":1720438315666,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"1","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error sending E2_TERM_INIT cause : RMR_ERR_NOENDPT - send//call could not find an endpoint based on msg type "}
ric_appmgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_e2mgr           | dial tcp 10.0.2.12:6379: i/o timeout
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_e2mgr exited with code 1
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_submgr          | dial tcp 10.0.2.12:6379: i/o timeout
ric_submgr          | {"ts":1720438397387,"crit":"ERROR","id":"submgr","mdc":{"CONTAINER_NAME":"ric_submgr","HOST_NAME":"ric_submgr_host","PID":"1","POD_NAME":"submgr_pod","SERVICE_NAME":"ric_submgr_service","SYSTEM_NAME":"oran_sc_ric","time":"2024-07-08T11:33:17"},"msg":"SDL: ReadAllSubscriptionsFromSdl(), GetAll(). Error while reading E2 subscriptions  keys from DBAAS dial tcp 10.0.2.12:6379: i/o timeout\n"}

**Comment by pgawlowicz** [comment]
which xapp do you run?

**Comment by lingyan98** [comment]
> which xapp do you run?

I haven't run any xapp now. I follow the quick start part shown in the read me. This is the first step " Launch the SC RIC".

**Comment by pgawlowicz** [comment]
hmm strange, i removed all containers and rebuilt the images, and it works out of the box, how do you run it ? in a VM?

**Comment by lingyan98** [comment]
> hmm strange, i removed all containers and rebuilt the images, and it works out of the box, how do you run it ? in a VM?

I run it on ubuntu22.04, not VM. I will try it again. Thank you for your reply!

**Comment by pgawlowicz** [comment]
seems that the `ric_submgr` is starting before the `ric_dbaas`, you can try to add the following in the `submgr:` section in the docker-compose.yml file:

```
  depends_on:
      - dbaas
```

**Comment by lingyan98** [comment]
> seems that the `ric_submgr` is starting before the `ric_dbaas`, you can try to add the following in the `submgr:` section in the docker-compose.yml file:
> 
> ```
>   depends_on:
>       - dbaas
> ```

I added this to `submgr:`, but I got the same result. My computer uses a fixed IP address and the DNS is 165.132.10.21 and 165.132.5.21. Does the DNS lead to failure to connect?

**Comment by pgawlowicz** [comment]
could you share your modified docker-compose.yaml file?

**Comment by lingyan98** [comment]
> could you share your modified docker-compose.yaml file?

I haven't modified the config file. My docker-compose.yaml is shown as follows:
```
version: '3.9'

services:
  dbaas:
    container_name: ric_dbaas
    hostname: dbaas
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-dbaas:${DBAAS_VER}
    command: redis-server --loadmodule /usr/local/libexec/redismodule/libredismodule.so
    networks:
      ric_network:
        ipv4_address: ${DBAAS_IP:-10.0.2.12}

  rtmgr_sim:
    container_name: ric_rtmgr_sim
    hostname: rtmgr_sim
    image: rtmgr_sim:${SC_RIC_VERSION}
    build:
      context: ./ric/images/rtmgr_sim
      dockerfile: ./Dockerfile
      args:
        SC_RIC_VERSION: ${SC_RIC_VERSION}
    env_file:
      - .env
    environment:
      - CONTAINER_NAME=ric_${RTMGR_SIM_NAME}
      - HOST_NAME=ric_${RTMGR_SIM_NAME}_host
      - POD_NAME=${RTMGR_SIM_NAME}_pod
      - SERVICE_NAME=ric_${RTMGR_SIM_NAME}_service
      - CFGFILE=/cfg/rtmgr-config.yaml
      - RMR_SEED_RT=/opt/config/uta-rtg.rt
      - RMR_SRC_ID=${RTMGR_SIM_IP}
    volumes:
      - type: bind
        source: ./ric/configs/rtmgr.yaml
        target: /opt/rmsimulator/resources/configuration.yaml
      - type: bind
        source: ./ric/configs/routes.rtg
        target: /opt/config/uta-rtg.rt
    networks:
      ric_network:
        ipv4_address: ${RTMGR_SIM_IP:-10.0.2.15}

  submgr:
    container_name: ric_submgr
    hostname: submgr
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-submgr:${SUBMGR_VER}
    env_file:
      - .env
    environment:
      - CONTAINER_NAME=ric_${SUBMGR_NAME}
      - HOST_NAME=ric_${SUBMGR_NAME}_host
      - POD_NAME=${SUBMGR_NAME}_pod
      - SERVICE_NAME=ric_${SUBMGR_NAME}_service
      - CFG_FILE=/opt/config/submgr-config.yaml
      - RMR_SEED_RT=/opt/config/submgr-uta-rtg.rt
      - RMR_SRC_ID=${SUBMGR_IP}
    command: ./submgr -f $${CFG_FILE}
    volumes:
      - type: bind
        source: ./ric/configs/submgr.yaml
        target: /opt/config/submgr-config.yaml
      - type: bind
        source: ./ric/configs/routes.rtg
        target: /opt/config/submgr-uta-rtg.rt
    networks:
      ric_network:
        ipv4_address: ${SUBMGR_IP:-10.0.2.13}
    depends_on:
        - dbaas        

  e2term:
    container_name: ric_e2term
    hostname: e2term
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-e2:${E2TERM_VER}
    env_file:
      - .env
    environment:
      - CONTAINER_NAME=ric_${E2TERM_NAME}
      - HOST_NAME=ric_${E2TERM_NAME}_host
      - POD_NAME=${E2TERM_NAME}_pod
      - SERVICE_NAME=ric_${E2TERM_NAME}_service
      - print=1
      - RMR_SEED_RT=/opt/e2/dockerRouter.txt
      - RMR_SRC_ID=${E2TERM_IP}
    command: ./e2 -p config -f config.conf
    volumes:
      - type: bind
        source: ./ric/configs/e2term.conf
        target: /opt/e2/config/config.conf
      - type: bind
        source: ./ric/configs/routes.rtg
        target: /opt/e2/dockerRouter.txt
    networks:
      ric_network:
        ipv4_address: ${E2TERM_IP:-10.0.2.10}

  appmgr:
    container_name: ric_appmgr
    hostname: appmgr
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-appmgr:${APPMGR_VER}
    env_file:
      - .env
    environment:
      - CONTAINER_NAME=ric_${APPMGR_NAME}
      - HOST_NAME=ric_${APPMGR_NAME}_host
      - POD_NAME=${APPMGR_NAME}_pod
      - SERVICE_NAME=ric_${APPMGR_NAME}_service
      - RMR_SEED_RT=/opt/ric/config/router.txt
      - RMR_SRC_ID=${APPMGR_IP}
    volumes:
      - type: bind
        source: ./ric/configs/routes.rtg
        target:  /opt/ric/config/router.txt
      - type: bind
        source: ./ric/configs/appmgr.yaml
        target: /opt/ric/config/appmgr.yaml
    networks:
      ric_network:
        ipv4_address: ${APPMGR_IP:-10.0.2.14}

  e2mgr:
    container_name: ric_e2mgr
    hostname: e2mgr
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-e2mgr:${E2MGR_VER}
    env_file:
      - .env
    environment:
      - CONTAINER_NAME=ric_${E2MGR_NAME}
      - HOST_NAME=ric_${E2MGR_NAME}_host
      - POD_NAME=${E2MGR_NAME}_pod
      - SERVICE_NAME=ric_${E2MGR_NAME}_service
      - RMR_SEED_RT=/opt/E2Manager/router.txt
      - RMR_SRC_ID=${E2MGR_IP}
    command: ./main -port=3800 -f /opt/E2Manager/resources/configuration.yaml
    volumes:
      - type: bind
        source: ./ric/configs/routes.rtg
        target: /opt/E2Manager/router.txt
      - type: bind
        source: ./ric/configs/e2mgr.yaml
        target: /opt/E2Manager/resources/configuration.yaml
    networks:
      ric_network:
        ipv4_address: ${E2MGR_IP:-10.0.2.11}

  python_xapp_runner:
    container_name: python_xapp_runner
    hostname: python_xapp_runner
    image: python_xapp_runner:${SC_RIC_VERSION}
    build:
      context: ./ric/images/ric-plt-xapp-frame-py
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - RMR_SEED_RT=/opt/ric/config/uta-rtg.rt
      - RMR_SRC_ID=${XAPP_PY_RUNNER_IP}
      - RMR_RTG_SVC # leave empty, so RMR works correctly with RT Manager Simulator
    stdin_open: true
    tty: true
    entrypoint: [/bin/bash]
    volumes:
      - type: bind
        source: ./ric/configs/routes.rtg
        target: /opt/ric/config/uta-rtg.rt
      - type: bind
        source: ./xApps/python
        target: /opt/xApps
      # Uncomment if you want to use your local ric-plt-xapp-frame-py copy inside the container
      #- type: bind
      #  source: ./Path/to/your/local/ric-plt-xapp-frame-py
      #  target: /opt/ric-plt-xapp-frame-py
    networks:
      ric_network:
        ipv4_address: ${XAPP_PY_RUNNER_IP:-10.0.2.20}

networks:
  ric_network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24

```

**Comment by lingyan98** [comment]
> could you share your modified docker-compose.yaml file?
I modified the port in e2term. The origin command is shown as follow:
```
  e2term:
    container_name: ric_e2term
    hostname: e2term
    image: nexus3.o-ran-sc.org:10004/o-ran-sc/ric-plt-e2:${E2TERM_VER}
```
With the  image: nexus3.o-ran-sc.org:10004/o-ran-sc/ric-plt-e2:${E2TERM_VER}. I got the following error:
`✘ e2term Error       manifest for nexus3.o-ran-sc.org:10004/o-ran-sc/ric-plt-e2:6.0.4 not found: manifest unknown: manifest unknown `
So I modified as follow
```
  e2term:
    container_name: ric_e2term
    hostname: e2term
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-e2:${E2TERM_VER}
```
