### ISSUE TITLE
OSC RIC: appmgr can’t connect to dbaas – config seems to be ignored

### ISSUE THREAD

**Issue by lmendyk** [srsran/oran-sc-ric#48]
I have follow this project, but still adapting it to be used in kubernetes,  but I think I get error not related to docker compose vs kubernetes.

When starting appmgr, in the logs I get:
```
dial tcp [::1]:6379: connect: connection refused
{"ts":1732200055823,"crit":"ERROR","id":"appmgr","mdc":{"CONTAINER_NAME":"","HOST_NAME":"","PID":"8","POD_NAME":"","SERVICE_NAME":"","SYSTEM_NAME":"","time":"2024-11-21T14:40:55Z","xm":"0.4.3"},"msg":"Database connection not ready, waiting ..."}
{"ts":1732200060849,"crit":"ERROR","id":"appmgr","mdc":{"CONTAINER_NAME":"","HOST_NAME":"","PID":"8","POD_NAME":"","SERVICE_NAME":"","SYSTEM_NAME":"","time":"2024-11-21T14:41:00Z","xm":"0.4.3"},"msg":"Database connection not ready, waiting ..."}
{"ts":1732200065875,"crit":"ERROR","id":"appmgr","mdc":{"CONTAINER_NAME":"","HOST_NAME":"","PID":"8","POD_NAME":"","SERVICE_NAME":"","SYSTEM_NAME":"","time":"2024-11-21T14:41:05Z","xm":"0.4.3"},"msg":"Database connection not ready, waiting ..."}
…
```
The config file seems to be correct as I verified it inside the appmgr container which seems adequate to the one from this project:
```
root@appmgr:/opt/ric/config# cat appmgr.yaml 
loglevel: 1
local:
  host: ":8080"
xapp:
  namespace: "ricxapp"
  tarDir: "/tmp"
  schema: "descriptors/schema.json"
  config: "config/config-file.json"
  tmpConfig: "/tmp/config-file.json"
db:
  sessionNamespace: "XMSession"
  host: "ric-dbaas-service-tcp:6379"
  prot: "tcp"
  maxIdle: 80
  maxActive: 12000
```

But when I change the db.host  I don't see that  being taken into account (I was experimenting with dummy ports etc  but still in the logs I can't see an attempt to use these parameters).

The submgr which has similar config file  with section "db" it works.
I have tried reviewing the code: https://github.com/o-ran-sc/ric-plt-appmgr/tree/i-release, I had found code fragments responsible for parsing for example: "xapp" part,  but I haven't found anything related to parsing "db" section of the config file.  On the other hand in this project there is the config with:
```
"db":
  "sessionNamespace": "XMSession"
  "host": "10.0.2.12:6379"

```
which I believe is equivalent of my:
```
db:
  sessionNamespace: "XMSession"
  host: "ric-dbaas-service-tcp:6379"
```
could you advice what I can do to have it working.

**Comment by pgawlowicz** [comment]
If you want to run the RIC with kubernetes, you can follow the official deployment guidelines from the ORAN SC RIC developers. 
This repo provides a minimized version that can run only with docker compose.

**Comment by lmendyk** [comment]
In fact I was doing that except that at the same time I was following this project treating them as guidelines how to simplify the configuration (in my case I have third pary RAN already working).  The original project has the config
https://gerrit.o-ran-sc.org/r/gitweb?p=ric-plt/ric-dep.git;a=blob;f=helm/appmgr/resources/appmgr.yaml;h=624003898790b3dc437eda7fb9d5bd28c779ff11;hb=HEAD
without the "db" section as in this project.  So I'm puzzled how this (docker composed) based can work

**Comment by pgawlowicz** [comment]
I took the appmgr config from here https://github.com/o-ran-sc/ric-plt-appmgr/blob/master/config/appmgr.yaml

but I do not think the appmgr is needed in the dockerized setup, as the xApps are started manually.

**Comment by lmendyk** [comment]
Yes, I have also seen this https://github.com/o-ran-sc/ric-plt-appmgr/blob/i-release/config/appmgr.yaml so I don't understand why it looks that the "db" part of the  config is ignored.

But this is helpful as I  just want to check the xAPP as in dockized version so I hope to have it migrated to this hybrid kuberntes-dockerized version :) 

> but I do not think the appmgr is needed in the dockerized setup, as the xApps are started manually.

Thanks.

**Comment by lmendyk** [comment]
FYI:  I managed to correct appmgr - I made a mistake when adopting original file and missed important part in appmgr_deployment (same in submgr_deployment):
```
            - configMapRef:
                name: {{ .Release.Name }}-dbaas-appconfig
```
And the content of dbass-appconifg is:
---
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dbaas-appconfig
data:
  DBAAS_NODE_COUNT: "1"
  DBAAS_SERVICE_HOST: {{ .Release.Name }}-dbaas-service-tcp
  DBAAS_SERVICE_PORT: "{{ .Values.dbaas.redisPort }}" 
```

So anyway the config for daas is not taken from appmgr.ymal  "das": section.
